spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=course;encrypt=true;trustServerCertificate=true
    username: sa
    password: AwesomePassword!

  jpa:
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
